### ISSUE TITLE
#getGroup bug

### ISSUE THREAD

**Issue by Xmonpl** [KekoSeries/KekoUtil#26]
#getGroup(Player p) return player UUID and not the name of the group it is in. 
In the #getGroupPrefix and #getGroupSuffix method, the world is required, but this method does not use it
![FOMCsbf](https://user-images.githubusercontent.com/31248347/93617961-efd12480-f9d6-11ea-8648-be8e213c7133.png)

**Comment by Xmonpl** [comment]
LuckyPerms work fine, bug is only in PermissionsEx

**Comment by portlek** [comment]
Can you try the 7.4.1 version?

**Comment by Xmonpl** [comment]
yeah, I'm gonna check

**Comment by Xmonpl** [comment]
Everything works! Thanks for your help!
